name: Build & Deploy Documentation site

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout, init and update submodules
        run: git submodule update --init --remote --recursive

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add all changes
        continue-on-error: true
        run: git add .
        
      - name: Commit changes
        continue-on-error: true
        run: |
          git commit -m "Update submodules"
          git push origin HEAD

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org" 

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            Source/.yarn/cache
            **/node_modules
            **/.eslintcache
            **/yarn.lock
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}

      - name: Build entire documentation site
        working-directory: ./Source
        run: yarn install 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Source/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
